# Generated by Django 3.1.13 on 2021-12-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pediatra',
            name='apellidos',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pediatra',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
